### PR TITLE
Allow passing KalmanFiltered type to smoothing process 

### PR DESCRIPTION
**Pull request by codles**
This can save some processing time. Also added a test

### CODE REVIEW

**Comment by codles** [comment]
@GordStephen 
The nightly build fails due to an SSL error. Thats not related to the code I touched.

```
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ECERTIFICATE, Class:SSL, The SSL certificate is invalid)
```

**Comment by GordStephen** [comment]
This looks great - I reran the failed tests and the SSL error is gone now, but now tests against the 0.5 nightlies give a lot of deprecation warnings that are causing problems and weird testing behaviour when the log file length maxes out... @milktrader what would you say to cutting off support (and tests) for `0.5-` independently of #46 (then we can pull this PR once tests are passing).

**Comment by GordStephen** [comment]
As a reference point, tests with nightlies on `master` fail now too - https://travis-ci.org/JuliaStats/TimeModels.jl

**Comment by milktrader** [comment]
Yes, I'm in favor of *not* supporting 0.5 for the time being. I'm doing that with TimeSeries, Quandl, MarketData, Timestamps and MarketTechnicals. It will be great once the dust settles, but for now it's probably a good way to avoid headaches.

**Comment by codles** [comment]
Tests are passing against v0.3 and v0.4. Removed v0.5 testing. as milktrader suggested above.

Ready to merge @GordStephen  @milktrader ?

**Comment by milktrader** [comment]
I'll go in now and start up on NEWS.md and files that will limit this to v0.3. Once we're satisfied that v0.3 is workable and stable, we can tag the last version and move on to isolating this package to work only on v0.4

**Pull request merged**
