### PR TITLE
Export type KalmanSmoothedMinimal

### PR DESCRIPTION
**Pull request by codles**

### CODE REVIEW

**Comment by milktrader** [comment]
From the travis log
````
ERROR: LoadError: LoadError: UndefVarError: ParametrizedMatrix not defined
````

**Comment by GordStephen** [comment]
Yes, good catch - unfortunately I was dumb and went for weeks again without submitting a PR, do you mind if we don't merge so as to avoid conflicts with #59 (which also fixes this)?

**Comment by codles** [comment]
@GordStephen no problem if you don't merge. As long as the issue gets fixed. I could have raised an issue but figured it would be less work for you to open a PR.

**Comment by GordStephen** [comment]
Ok, just pulled #59 which should fix it.

**Pull request closed without merging**
