### PR TITLE
  Edit Allow evolution and observation matrix to vary with time (2)

### PR DESCRIPTION
**Pull request by codles**
Refactor of #32 

Added test first for old code

### CODE REVIEW

**Comment by codles** [comment]
Why is travis not testing this?

**Comment by codles** [comment]
There appears to be a bug in fit which I have got around by running simulate twice.

**Comment by codles** [comment]
Ok you are testing against v0.4. I will have to make changes for this

**Comment by codles** [comment]
@scidom @milktrader I needed to change the travis file to get things working. But I think this is ready now.

**Comment by milktrader** [comment]
Ok, we'll go with this.

**Pull request merged**
